import assert from 'node:assert/strict';
import {createParserExecutor} from '../../runtime/parser_executor.mjs';
import {createParserSandbox} from '../../runtime/inquiry_sandbox.mjs';
import {rawRecords,globalState} from '../consumers/incremental-parser/candidates.mjs';
const executor=await createParserExecutor();
assert.equal(executor.kind,'qualified');
const history=Array.from({length:500},(_,i)=>({chunk:[65+i%26,10],endOfInput:false}));
history.push({chunk:[],endOfInput:true});
for(let attempt=0;attempt<3;attempt++) {
  const before=executor.metrics().physicalExecutions;
  const result=await executor.probe(rawRecords,history);
  assert.equal(result.kind,'completed');assert.equal(result.passed,true);
  assert(executor.metrics().physicalExecutions-before>1,'long traces retire physical workers');
}
const split=Array.from({length:62},()=>({chunk:[65],endOfInput:false}));
split.push({chunk:[92],endOfInput:false},{chunk:[120],endOfInput:true});
assert.equal((await executor.probe(rawRecords,split)).passed,true,'offset and escape state cross workers');
assert.equal((await executor.probe(globalState,split)).passed,false,'module globals do not cross calls');
const snapshot=await createParserSandbox({timeoutMs:10000,maximumOutputBytes:1048576});
const mutable=Array.from({length:80},()=>({chunk:[65],endOfInput:false}));
mutable.push({chunk:[10],endOfInput:true});
const pending=snapshot.execute(rawRecords,mutable);
mutable[64].chunk[0]=66;
const observed=await pending;
assert.equal(observed.kind,'completed');
assert.deepEqual(observed.rows.at(-1).newly_completed_records,[[Array(80).fill(65)]]);
const bounded=await createParserSandbox({timeoutMs:1000,maximumOutputBytes:4096});
assert.equal(bounded.kind,'qualified');
const simple=`export const initial=()=>({n:0});export function step(s){s.n++;return {next_state:s,newly_completed_records:[],status:'open'};}`;
const trace=Array.from({length:128},()=>({chunk:[],endOfInput:false}));
const output=await bounded.execute(simple,trace);
assert.equal(output.kind,'output_limit');assert(!Object.hasOwn(output,'rows'));
const slow=simple.replace('s.n++;',"const end=Date.now()+10;while(Date.now()<end){}s.n++;");
const deadline=await createParserSandbox({timeoutMs:1000,maximumOutputBytes:1048576});
const timed=await deadline.execute(slow,trace);
assert.equal(timed.kind,'timeout');assert(timed.physicalExecutions>1);assert(!Object.hasOwn(timed,'rows'));
const failed=await bounded.execute(simple.replace('s.n++;',"if(s.n===40)throw new Error('late');s.n++;"),trace);
assert.equal(failed.kind,'execution_failed');assert(failed.physicalExecutions>1);assert(!Object.hasOwn(failed,'rows'));
const small=await createParserSandbox({timeoutMs:1000,maximumOutputBytes:1024});
const largeState=`export const initial=()=>({data:'x'.repeat(32768)});export const step=s=>({next_state:s,newly_completed_records:[],status:'open'});`;
assert.equal((await small.execute(largeState,trace.slice(0,1))).kind,'completed','final state does not consume observation output budget');
console.log(JSON.stringify({check:'parser realm retirement',longTraceAttempts:3,logicalLimits:true,stateContinuity:true,freshRealms:true}));
